# Generated by Django 3.0.2 on 2020-01-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
